;METADATA=(Diff=true, UseCommands=true)
[/Script/Engine.GameUserSettings]
bUseDesiredScreenHeight=False

[ScalabilityGroups]
sg.ResolutionQuality=100
sg.ViewDistanceQuality=0
sg.AntiAliasingQuality=0
sg.ShadowQuality=4
sg.GlobalIlluminationQuality=0
sg.ReflectionQuality=0
sg.PostProcessQuality=0
sg.TextureQuality=0
sg.EffectsQuality=0
sg.FoliageQuality=0
sg.ShadingQuality=0
sg.LandscapeQuality=0
sg.AnimationQuality=0

[/Script/DeadByDaylight.DBDGameUserSettings]
DeviceLoginTokenID=
ScalabilityLevel=0
AutoScalabilitySet=False
AutoAdjust=False
ScreenRenderSize=100
HUDConstrainedAspectRatio=True
MenuScaleFactor=80
HudScaleFactor=80
SkillCheckScaleFactor=100
LargeText=False
BloodwebInteractionBehaviour=True
TerrorRadiusVisualFeedback=True
DeepWoundBarVisibility=True
FieldOfView=103
HUDPlayerNamesVisibility=True
HUDKillerHookCountVisibility=True
HUDScoreEventsVisibility=True
HUDUseItemPickupPopupAbridgedVersion=False
LegacyPrestigePortraits=False
PrestigePortraitStyle=2
ShowHudStatusEffectValueNumber=True
FPSLimitMode=120
AntiAliasingMode=0
EnableFSR=False
SharpnessValue=3.000000
XeSSMode=0
MainVolume=0
MainVolumeOn=True
MenuMusicVolume=0
MenuMusicVolumeOn=False
UseHeadphones=False
MuteOnFocusLost=True
HapticsVibrationPS5=True
KillerCameraSensitivity=50
SurvivorCameraSensitivity=50
KillerMouseSensitivity=65
SurvivorMouseSensitivity=65
KillerControllerSensitivity=65
SurvivorControllerSensitivity=100
AimAssist=False
ControlType=1
InvertY=False
SurvivorInvertY=False
SurvivorInvertYAxisController=False
SurvivorInvertYAxisMouse=False
KillerInvertYAxisController=False
KillerInvertYAxisMouse=False
KillerToggleInteractions=False
SurvivorToggleInteractions=True
SprintToCancel=False
Language=en
VoiceOverLanguage=1
LanguageIsDefinedByPlayer=False
HighestWeightSeenNews=0
SharedLoginInformation=(LoginProvider="",AuthToken="",TokenType="")
LastPanelContextId=0
HasAcceptedCrossplayPopup=True
HasAcceptedHapticsVibrationPopup=False
UseAtlantaCustomizedHuds=False
UseAtlantaSurvivorQuickTurn=True
UseAtlantaKillerQuickTurn=True
PartyPrivacyState=private
ColorBlindMode=1
ColorBlindModeIntensity=0
BeginnerMode=False
Subtitles=False
SubtitlesBackgroundOpacity=1
SubtitlesSize=1
IsAnonymousMode=True
AllowCopyrightedMusic=False
HideYourName=False
HideOtherNames=False
HiddenMatchmakingDelay=False
PlayerCardAnimationMode=0
AnimateRarityBackgrounds=False
ScratchMarksColor=(B=75,G=0,R=184,A=255)
AuraColors=(((TagName="Aura.Type.Objective.Hook.State.Hooked"), (B=0,G=170,R=170,A=255)),((TagName="Aura.Type.Object.Pallet"), (B=0,G=89,R=170,A=255)),((TagName="Aura.Type.Object.Pallet.K36.PotentialTarget"), (B=0,G=89,R=170,A=255)),((TagName="Aura.Type.Object.Marked"), (B=0,G=170,R=170,A=255)),((TagName="Aura.Type.Objective.KillerObject.State.Marked"), (B=0,G=170,R=170,A=255)),((TagName="Aura.Type.Objective.Marked"), (B=0,G=170,R=170,A=255)),((TagName="Aura.Type.Object.Window"), (B=0,G=89,R=170,A=255)),((TagName="Aura.Type.Object.BreakableWall"), (B=89,G=124,R=63,A=255)),((TagName="Aura.Type.Objective.KillerObject"), (B=179,G=179,R=179,A=255)),((TagName="Aura.Type.Character.Survivor"), (B=108,G=66,R=160,A=255)),((TagName="Aura.Type.Character.Killer"), (B=108,G=66,R=160,A=255)),((TagName="Aura.Type.Object.Surfaced"), (B=0,G=170,R=170,A=255)),((TagName="Aura.Type.Objective.KillerObject.State.Surfaced"), (B=0,G=170,R=170,A=255)),((TagName="Aura.Type.Objective.Surfaced"), (B=0,G=170,R=170,A=255)),((TagName="Aura.Type.Objective.Generator.Repair.HighestProgression"), (B=0,G=170,R=170,A=255)))
TomesChallengeNotification=0
DailyChallengeNotification=1
EventChallengeNotification=1
BattlePassChallengeNotification=1
MilestoneChallengeNotification=1
OnboardingChallengeNotification=1
ArchivesAutoPlayVoiceOver=True
ArchivesFullscreenTextVisibility=True
Gamma=2.200000
SpectatorHudPlayersHotkeys=True
SpectatorHudKillerPreview=True
bUseVSync=False
bUseDynamicResolution=False
ResolutionSizeX=2560
ResolutionSizeY=1440
LastUserConfirmedResolutionSizeX=2560
LastUserConfirmedResolutionSizeY=1440
FullscreenMode=1
LastConfirmedFullscreenMode=1
PreferredFullscreenMode=1
Version=5
AudioQualityLevel=4
LastConfirmedAudioQualityLevel=4
FrameRateLimit=120.000000
DesiredScreenWidth=2560
DesiredScreenHeight=1440
LastUserConfirmedDesiredScreenWidth=2560
LastUserConfirmedDesiredScreenHeight=1440
LastRecommendedScreenWidth=-1.000000
LastRecommendedScreenHeight=-1.000000
LastCPUBenchmarkResult=288.481903
LastGPUBenchmarkResult=927.111755
LastGPUBenchmarkMultiplier=1.000000
bUseHDRDisplayOutput=False
HDRDisplayOutputNits=1000
LastCPUBenchmarkSteps=293.541168
LastCPUBenchmarkSteps=285.109039
LastGPUBenchmarkSteps=1758.051270
LastGPUBenchmarkSteps=1260.219849
LastGPUBenchmarkSteps=2347.001465
LastGPUBenchmarkSteps=781.632874
LastGPUBenchmarkSteps=357.309174
LastGPUBenchmarkSteps=381.377197
LastGPUBenchmarkSteps=1854.901001
WindowPositions=(X=0,Y=0)

